- 99
  - Cycling Through CAM Objects éå† CAM å¯¹è±¡
<details>
<summary> æˆªå›¾ </summary>

![6531697786983_ pic_hd](https://github.com/ChenxingWang93/Using-NX-Open-to-Improve-Workflows/assets/31954987/96743e54-49c0-4c4f-8893-003a4a25c9af)
</details>

``` vb
Dim workPart As Part = NXOpen.Session.GetSession.Parts.Work
Dim setup As NXOpen.CAM.CAMSetup = workPart.CAMsetup
```

#### Cycling through CAM Objects

``` vb
Dim setup As NXOpen.CAMSetup = workPart.CAMSetup
Dim opCollection As NXOpen.CAM.OperationCollection = setup.CAMOperationCollection

For Each op As NXOpen.CAM.Operation In opCollection
   Dim opType As System.Type = op.GetType
   Guide.InfoWriteLine(opType.ToString)
Next
```

``` vb
Dim setup As NXOpen.CAM.CAMSetup = workPart.CAMSetup
Dim groups As NXOpen.CAM.NCGroupCollection = setup.CAMGroupCollection

For Each group As NXOpen.CAM.NCGroup In groups
   If TypeOf(group) Is NXOpen.CAM.Tool = DirectCast(group, NXOpen.CAM.Tool)
   Dim toolType As NXOpen.CAM.Tool.Types                /*ç±»å‹*/
   Dim toolSubType As NXOpen.CAM.Tool.Subtypes          /*äºšå‹*/
   tool.GetTypeAndSubtype(toolType, toolSubType)        /**/
   Guide.InfoWriteLine("Tool type:    " & toolType.ToString)
   Guide.InfoWriteLine("Tool subtypes:" & toolSubType.ToString)
```

- 100
  - editing CAM Objects ç¼–è¾‘ CAM å¯¹è±¡
<details>
<summary> æˆªå›¾ </summary>
  
![6541697786989_ pic_hd](https://github.com/ChenxingWang93/Using-NX-Open-to-Improve-Workflows/assets/31954987/7e46ddc2-d639-4427-965b-6f08ce95b085)
</details>

``` vb
Dim setup As NXOpen.CAM.CAMSetup = workPart.CAMSetup
Dim opCollection As NXOpen.CAM.OperationCollection = setup.CAMOperationCollection

For Each op As NXOpen.CAM.Operation In opCollection
   If TypeOf(op) Is NXOpen.CAM.HoleDrilling Then
      Dim drillop As CAM.HoleDrilling = CType(op, CAM.HoleDrilling)
      Dim builder As CAM.HoleDrillingBuilder = opCollection.CreateHoleDrillingBuilder(drillop)
      builder.CollisionCheck = True
      builder.Commit
   End If
Next
```

|Function å‡½æ•°|Creates a builder for åˆ›å»ºä¸€ä¸ª|
|-------------|-----------------------------|
|CreateCavityMillingBuilder          |A planar milling cavity operation å¹³é¢é“£å‰Šæ‰“å­”æ“ä½œ     |
|CreateCenterlineDrillTurningBuilder |A centerline drill turning operation ä¸­å¿ƒçº¿æ‰“å­”è½¬åŠ¨æ“ä½œ|
|CreateEngravingBuilder              |A planar milling text operation å¹³é¢é“£å‰Šæ–‡å­—æ“ä½œ       |
|CreateFaceMillingBuilder            |A planar milling facing operation å¹³é¢é“£å‰Šæ–‡å­—æ“ä½œ     |
|CreateHoleDillingBuilder            |A hole drilling operation æ‰“å­”æ“ä½œ                    |
|CreatePlanarMillingBuilder          |A planar milling planar operation é“£å‰Šå¹³é¢æ“ä½œ         |


|Function å‡½æ•°|Creates a builder for åˆ›å»ºä¸€ä¸ª|
|-------------|-----------------------------|
|CreateBarrelToolBuilder|A barrel tool æ¡¶å·¥å…·|
|CreateDrillGeomBuilder |A drill geometry ä¸€ç§æ‰“å­”å‡ ä½•|
|CreateDrillMethodBuilder|A drill method  ä¸€ç§æ‰“å­”æ–¹æ³•|
|CreateDrillTapToolBuilder|A drill tap tool ä¸€ç§é’»ä¸é”¥å·¥å…·|
|CreateMachineTurretGroupBuilder|A machine turret group|
|CreateMillToolBuilder|A mill tool|
|CreateMillGeomBuilder|A mill geometry|
|CreateProgramOrderGroupBuilder|A program order group|


- 101
  - CAM views CAM è§†å›¾
<details>
<summary> æˆªå›¾ </summary>

![6551697786995_ pic_hd](https://github.com/ChenxingWang93/Using-NX-Open-to-Improve-Workflows/assets/31954987/675db386-be45-4e1f-b0c3-a7ea43625835)
</details>

``` vb
Dim setup As NXOpen.CAM.CAMSetup = workPart.CAMSetup
Dim groups As NXOpen.CAM.NCGroupCollection = setup.CAMGroupCollection

For Each group As NXOpen.CAM.NCGroup In groups
   If TypeOf(group) Is NXOpen.CAM.Tool Then
      Dim toolType As NXOpen.CAM.Tool.Types
      Dim toolSubType As NXOpen.CAM.Tool.Subtypes
      tool.GetTypeAndSubtype(toolType, toolSubtype)
      If toolType = CAM.Tool.Types.Mill
         Dim builder As NXOpen.CAM.MillingToolBuilder = groups.CreateMillToolBuilder(tool)
         builder.CoolantThrough = True
         builder.Commit
      End If
    End If
Next Next
```

#### ProgramView ç¨‹åºè§†å›¾

#### MachineToolView æœºæ¢°å·¥å…·è§†å›¾

#### GeometryView å‡ ä½•è§†å›¾

#### MethodView æ–¹æ³•è§†å›¾

``` vb
Dim setup As NXOpen.CAM.CAMSetup = workPart.CAMSetup

Dim geometryRoot As NXOpen.CAM.NCGroup = setup.GetRoot(NXOpen.CAM.CAMSetup.View.Geometry)
Dim methodRoot   As NXOpen.CAM.NCGroup = setup.GetRoot(NXOpen.CAM.CAMSetup.View.MachineMethod)
Dim machineRoot  As NXOpen.CAM.NCGroup = setup.GetRoot(NXOpen.CAM.CAMSetup.View.ProgramOrder)

Dim geometryRootMembers As NXOpen.CAM.CAMObject() = geometryRoot.GetMembers
Dim methodRootMembers   As NXOpen.CAM.CAMObject() =   methodRoot.GetMembers
Dim machineRootMembers  As NXOpen.CAM.CAMObject() =  machineRoot.GetMembers
Dim programRootMembers  As NXOpen.CAM.CAMObject() =  programRoot.GetMembers
```

- 102
  - Creating a Tool åˆ›å»ºä¸€ä¸ªå·¥å…·ğŸ”§
<details>
<summary> æˆªå›¾ </summary>

![6561697787001_ pic_hd](https://github.com/ChenxingWang93/Using-NX-Open-to-Improve-Workflows/assets/31954987/61d9e88a-6203-4f20-9859-70b86613ee74)
</details>

``` vb
Dim setup As NXOpen.CAM.CAMSetup = workPart.CAMSetup
Dim group As NXOpen.CAM.NCGroupCollection = setup.CAMGroupCollection
Dim machineRoot As NXOpen.CAM.NCGroup = setup.GetRoot(NXOpen.CAM.CAMSetup.View.MachineTool)

Dim camFalse As CAM.NCGroupCollection.UseDefaultName = CAM.NCGroupCollection.UseDefaultName.False

Dim toolGroup As CAM.NCGroup
toolGroup = groupCollection.CreateTool(machineRoot, "mill_planar", "BALL_MILL", camFalse, "T24")
Dim myTool As CAM.Tool = CType(toolGroup, CAM.Tool)
```

|Tool Type å·¥å…·ç±»å‹|Tool Subtype å·¥å…·äºšå‹          |
|-----------------|-----------------------------|
|mill_planar      |MILLé“£å‰Š                      |
|mill_planar      |CHAMFER_MILLå€’è§’é“£å‰Š           |
|mill_planar      |BALL_MILLçƒä½“é“£å‰Š              |
|mill_planar      |SPHERICAL_MILLçƒå½¢é“£å‰Š         |
|mill_planar      |T_CUTTERTå‹åˆ‡                 |
|mill_planar      |BARRELæ¡¶                      |
|hole_making      |COUNTER_SINKæŸœå°_æ°´æ§½          |
|hole_making      |COUNTER_BOREæ²‰å­”              |
|drill            |COUNTERSINKING_TOOLæŸœå°_æ°´æ§½å·¥å…·|
|drill            |COUNTERBORING_TOOLæ²‰å­”å·¥å…·     |

``` vb
Dim toolBuilder As CAM.MillToolBuilder = groupCollection.CreateMillToolBuilder(myTool)

toolBuilder.TlDiameterBuilder.Value = 4.5
toolBuilder.TlHeightBuilder.Value = 15
toolBuilder.TlHeightBuilder.Value = 4
toolBuilder.Description = "Example ball mill"
toolBuilder.HelicalDiameter.Value = 80.0

toolBuilder.Commit

toolBuilder.Destroy
```
